### ISSUE TITLE
amf.write()

### ISSUE THREAD

**Issue by celorodovalho** [TooTallNate/node-amf#1]
Where is the "write" method?

**Comment by TooTallNate** [comment]
Not yet implemented :)

Hopefully I'll get around to it soon, but I don't have an immediate need for it. Patch welcome of course!

**Comment by celorodovalho** [comment]
Hm! Thanks!
Im trying to connect my app in Flex with NodeJS throught of AMFChannel of the AS3.
Maybe you can help me write a lib to this kind of connection, coz i tryed to use your lib, and node-amf module of the Tim WhiteLock too without success. :/
